### ISSUE TITLE
$Stripe is not available within a function

### ISSUE THREAD

**Issue by StirStudios** [dogchef-be/nuxt-stripejs#6]
We are currently using nuxt-stripe-module and we are looking to migrate to this module instead as we are encountering a performance hit across all pages. Your module is loading Stripe.js only when needed which is perfect.

That said here is the problem.

async mounted works well for the card element:

```
if (this.$stripe) {
  const stripe = await this.$stripe()
  const elements = stripe.elements()

  const style = {
    base: {
      iconColor: '#adb5bd',
      color: '#adb5bd',
      fontWeight: '400',
      fontFamily: 'Roboto, Open Sans, Segoe UI, sans-serif',
      fontSize: '16px',
      fontStyle: 'italic',
      fontSmoothing: 'antialiased',
      ':-webkit-autofill': {
        color: '#adb5bd',
      },
        '::placeholder': {
        color: '#adb5bd',
      },
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a',
    },
  }
  const card = elements.create('card', { style: style })
  card.mount(this.$refs.stripeElements)
}
```

However when we create a token we always get the following error:

this.$stripe.createToken is not a function

```
this.$stripe
  .createToken(this.card, {
    name: this.nameOnCard,
    address_zip: this.billingZip,
    address_country: this.country,
  })
```

This is the same as what we use with nuxt-stripe-module but I know that #stripe is globally available.

Any suggestions would be greatly appreciated.

**Comment by fabiofdsantos** [comment]
@StirStudios, thanks for considering our module!

```
const stripe = await this.$stripe();
stripe.createToken(...)
```

PS: You don't need to check `if (this.$stripe) ...`

**Comment by StirStudios** [comment]
@fabiofdsantos it now works like a charm!! We have removed the `if (this.$stripe) ....` residual from the other Stripe module. Once we included the `const stripe = await this.$stripe()` again in the function everything worked! Awesome.

Now we get the benefits of Stripe loaded only when needed and much better performance overall!
